Add behavior IVersionable to Portal
plone/plone.app.versioningbehavior pull request #87
Opened 2024-10-03 15:33 UTC by wesleybl

This is part of: https://github.com/plone/volto/issues/5284

In order for the working copy of `plone.app.iterate` to work in the Portal, it needs to be versionable and have the IVersionable behavior. See:

https://github.com/plone/plone.app.iterate/blob/1908aa1f4e9c95c37143fae88655469b72ea451a/plone/app/iterate/browser/control.py#L50-L52

2024-10-03 15:33 UTC, mister-roboto commented
@wesleybl thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-10-03 15:37 UTC, wesleybl commented
@jenkins-plone-org please run jobs

2024-10-11 22:31 UTC, mauritsvanrees reviewed
What I don't like about this, is that we would then have two behaviors: `plone.versioning` and `plone.versioning.portal`.  This is visible in the   Isn't there some interface that is shared between the Plone Site root and normal Dexterity content?

2024-10-15 21:00 UTC, davisagli requested changes
@wesleybl Like Maurits, I don't understand why a new behavior is needed. Can't we just enable the existing behavior for the Plone Site content type? The portal object should have the IDexterityContent interface starting in Plone 6.0.

2024-10-16 13:46 UTC, wesleybl commented
> The portal object should have the IDexterityContent interface starting in Plone 6.0

@mauritsvanrees @davisagli this is true when you create a Classic Plone Site. But when you create a modern Plone Site, something happens and it stops working. This may require further investigation.

2024-11-04 19:27 UTC, wesleybl commented
@mauritsvanrees @davisagli I did a test here and there really is no need for new behavior.

2024-11-04 19:27 UTC, closed without merging